version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ddd_sevice
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ddd_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data

networks:
  backend:

